# generate_theme_header.cmake
# Reads GLSL shader source files and generates a theme .h header.
#
# Parameters (passed via -D):
#   OUTPUT    - Path to the output .h file
#   NAMESPACE - C++ struct name (e.g. "theme_gpt")
#   NAME      - Display name (e.g. "GPT")
#   BASE      - Base struct to inherit from (e.g. "ThemeDefaults")
#   SHADERS   - Semicolon-separated list of "VARNAME=filepath" pairs
#               (e.g. "kVert=vis.vert;kFrag=vis.frag")

message(STATUS "==start")

if(NOT OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT NAMESPACE)
    message(FATAL_ERROR "NAMESPACE is required")
endif()
if(NOT NAME)
    message(FATAL_ERROR "NAME is required")
endif()
if(NOT BASE)
    message(FATAL_ERROR "BASE is required")
endif()

# Write header
file(WRITE "${OUTPUT}" "// Auto-generated by CMake from shader source files - DO NOT EDIT\n")
file(APPEND "${OUTPUT}" "#pragma once\n\n")
file(APPEND "${OUTPUT}" "struct ${NAMESPACE} : ${BASE} {\n")
file(APPEND "${OUTPUT}" "    static constexpr const char* kName = \"${NAME}\";\n")

if(SHADERS)
    foreach(SHADER_PAIR ${SHADERS})
        string(REPLACE "=" ";" PAIR "${SHADER_PAIR}")
        list(GET PAIR 0 VAR_NAME)
        list(GET PAIR 1 SHADER_FILE)

        if(NOT EXISTS "${SHADER_FILE}")
            message(FATAL_ERROR "Shader file not found: ${SHADER_FILE}")
        endif()

        file(READ "${SHADER_FILE}" CONTENT)

        file(APPEND "${OUTPUT}" "\n    static constexpr const char* ${VAR_NAME} = R\"glsl(\n")
        file(APPEND "${OUTPUT}" "${CONTENT}")
        file(APPEND "${OUTPUT}" "\n)glsl\";\n")
    endforeach()
endif()

file(APPEND "${OUTPUT}" "\n}; // struct ${NAMESPACE}\n")

message(STATUS "==Generated: ${OUTPUT}")
