/**
 * This file was generated by bin2cpp v3.1.0
 * Copyright (C) 2013-2025 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'fa-solid-900.ttf', last modified 1779270810.
 * Do not modify this file.
 */
#ifndef FA_SOLID_900_H
#define FA_SOLID_900_H

#include <stddef.h>

namespace bin2cpp
{
  #ifndef BIN2CPP_FILE_OBJECT_CLASS
  #define BIN2CPP_FILE_OBJECT_CLASS
  class File
  {
  public:
    virtual size_t getSize() const = 0;
    /* DEPRECATED */ virtual inline const char * getFilename() const { return getFileName(); }
    virtual const char * getFileName() const = 0;
    virtual const char * getFilePath() const = 0;
    virtual const char * getBuffer() const = 0;
    virtual bool save(const char * filename) const = 0;
  };
  #endif //BIN2CPP_FILE_OBJECT_CLASS
  const File & getFasolid900TtfFile();
}; //bin2cpp

#endif //FA_SOLID_900_H
